### ISSUE TITLE
Bad NSHealthShareUsageDescription and absent BGTaskSchedulerPermittedIdentifiers

### ISSUE THREAD

**Issue by indapublic** [sahha-ai/sahha-react-native-integration-tutorial#1]
<img width="752" alt="image" src="https://github.com/sahha-ai/sahha-react-native-integration-tutorial/assets/856260/439ec0fb-e355-4393-a2cc-5c2cb51a0165">

**Comment by smileypop** [comment]
1. Please follow these steps to add the missing usage description to your project:

https://docs.sahha.ai/docs/guides/sdk/setup#step-3-add-usage-descriptions

2. The SDK no longer requires the Background Modes capability, so you can remove that entirely.
